const Actions = {
  RESET: 'RESET',
  USER: {
    KEY: 'USER',
    TYPE: {
      SAVE_USER_DATA: 'SAVE_USER_DATA',
      CLEAR_USER_DATA: 'CLEAR_USER_DATA',
      CLEAR_ALL_ORDER_DETAILS: 'CLEAR_ALL_ORDER_DETAILS',
      GET_USER_ADDRESSES: 'GET_USER_ADDRESSES',
      SAVE_PAGE_URLS: 'GET_PAGE_URLS',
      SAVE_USER_ADDRESS: 'SAVE_USER_ADDRESS',
      SELECT_ADDRESS_FOR_PAYMENT: 'SELECT_ADDRESS_FOR_PAYMENT',
      SELECT_ADDRESS_AND_SAVE_SHIPPING_METHODS:
        'SELECT_ADDRESS_AND_SAVE_SHIPPING_METHODS',
      SAVE_SELECTED_SHIPPING_METHOD_CODE: 'SAVE_SELECTED_SHIPPING_METHOD_CODE',
      SAVE_AVAILABLE_PAYMENT_METHODS: 'SAVE_AVAILABLE_PAYMENT_METHODS',
      SAVE_ORDER_DETAILS: 'SAVE_ORDER_DETAILS',
      SAVE_SUCCESS_ORDER_WITH_DATA: 'SAVE_SUCCESS_ORDER_WITH_DATA',
      SAVE_RAZORPAY_ORDER_DETAILS: 'SAVE_RAZORPAY_ORDER_DETAILS',
      SAVE_RAZORPAY_CONFIRMATION_RES: 'SAVE_RAZORPAY_CONFIRMATION_RES',
      SAVE_COUPON_CODE: 'SAVE_COUPON_CODE',
    },
  },
  LAYOUT: {
    KEY: 'LAYOUT',
    TYPE: {
      SHOW_LOADER: 'SHOW_LOADER',
      HIDE_LOADER: 'HIDE_LOADER',
      CART_BADGE: 'CART_BADGE',
    },
  },
  CART_DATA: {
    KEY: 'CART',
    TYPE: {
      GET_CART_DATA: 'GET_CART_DATA',
    },
  },
};

export default Actions;
