const StoreKeys = {
  USER: {
    DATA: 'USER_DATA',
    ADDRESSES: 'ADDRESSES',
    SELECTED_ADDRESS_ID_FOR_PAYMENT: 'SELECTED_ADDRESS_ID_FOR_PAYMENT',
    SELECTED_SHIPPING_METHOD_CODE: 'SELECTED_SHIPPING_METHOD_CODE',
    SHIPPING_METHODS: 'SHIPPING_METHODS',
    AVAILABLE_PAYMENT_METHODS: 'AVAILABLE_PAYMENT_METHODS',
    ORDER_DETAILS: 'ORDER_DETAILS',
    RAZORPAY_ORDER_DETAILS: 'RAZORPAY_ORDER_DETAILS',
    RAZORPAY_CONFIRMATION_RES: 'RAZORPAY_CONFIRMATION_RES',
    ORDER_STATUS: 'ORDER_STATUS',
    ORDERED_ITEMS: 'ORDERED_ITEMS',
    PAGE_URLS: 'PAGE_URLS',
    COUPON_CODE: 'COUPON_CODE',
    VALID_COUPON_CODE: false,
    COUPON_MSG: 'COUPON_MSG',
    EJ_CASH_APPLIED: 'EJ_CASH_APPLIED',
  },
  LAYOUT: {
    LOADER: 'LOADER',
    CART_BADGE: 'CART_BADGE',
    //STORE_BADGE: 'STORE_BADGE'  
  },
  SHOW_LOADER: 'SHOW_LOADER',
  CART_DATA: 'CART_DATA'
};

export default StoreKeys;
